controller_list:
  - name: jaco_arm
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - jaco_arm_joint_1
      - jaco_arm_joint_2
      - jaco_arm_joint_3
      - jaco_arm_joint_4
      - jaco_arm_joint_5
      - jaco_arm_joint_6
      - jaco_arm_joint_7
