controller_list:
  - name: fake_manipulator_controller
    joints:
      - jaco_arm_joint_1
      - jaco_arm_joint_2
      - jaco_arm_joint_3
      - jaco_arm_joint_4
      - jaco_arm_joint_5
      - jaco_arm_joint_6
      - jaco_arm_joint_7