controller_list:
  - name: fake_left_manipulator_controller
    joints:
      - left_mico_arm_joint_1
      - left_mico_arm_joint_2
      - left_mico_arm_joint_3
      - left_mico_arm_joint_4
      - left_mico_arm_joint_5
      - left_mico_arm_joint_6
  - name: fake_right_manipulator_controller
    joints:
      - right_mico_arm_joint_1
      - right_mico_arm_joint_2
      - right_mico_arm_joint_3
      - right_mico_arm_joint_4
      - right_mico_arm_joint_5
      - right_mico_arm_joint_6