controller_list:
  - name: fake_manipulator_controller
    joints:
      - mico_arm_joint_1
      - mico_arm_joint_2
      - mico_arm_joint_3
      - mico_arm_joint_4
      - mico_arm_joint_5
      - mico_arm_joint_6